dataroot: "/home/haoyuefan/AirSLAM_src/src/data/euroc/mav0"
camera_config_path: "/home/haoyuefan/AirSLAM_src/src/configs/euroc.yaml"
model_dir: "/home/haoyuefan/AirSLAM_src/src/output"
saving_dir: "/home/haoyuefan/AirSLAM_src/src/debug"

superpoint:
  max_keypoints: 700
  keypoint_threshold: 0.005
  remove_borders: 4 
  input_tensor_names: 
    - "input"
  output_tensor_names:
    - "scores"
    - "descriptors"
  onnx_file: "superpoint_v1_sim.onnx"
  engine_file: "superpoint_v1_sim.engine"
  dla_core: -1

superglue:
  image_width: 752
  image_height: 480
  input_tensor_names:
    - "keypoints_0"
    - "scores_0"
    - "descriptors_0"
    - "keypoints_1"
    - "scores_1"
    - "descriptors_1"
  output_tensor_names:
    - "scores"
  onnx_file: "superglue_indoor_sim.onnx"
  engine_file: "superglue_indoor_sim.engine"
  dla_core: -1

keyframe:
  min_num_match: 30
  max_num_match: 250
  max_distance: 0.5
  max_angle: 0.52

ros_publisher:
  feature: 1
  feature_topic: "/AirSLAM/feature"
  frame_pose: 1
  frame_pose_topic: "/AirSLAM/frame_pose"
  keyframe: 1
  keyframe_topic: "/AirSLAM/keyframe"
  path_topic: "/AirSLAM/odometry"
  map: 1
  map_topic: "/AirSLAM/map"
 
