dataroot: "/home/haoyuefan/xk_data/top_view/shahe/daytime"
camera_config_path: "/home/xukuan/code/superpoint-superglue-with-tensorrt/configs/realsense_848_480.yaml"
model_dir: "/home/xukuan/code/superpoint-superglue-with-tensorrt/model"
saving_dir: "/home/xukuan/code/superpoint-superglue-with-tensorrt/saving"

superpoint:
  max_keypoints: 700
  keypoint_threshold: 0.005
  remove_borders: 4 
  input_tensor_names: 
    - "input"
  output_tensor_names:
    - "scores"
    - "descriptors"
  onnx_file: "superpoint_480x848_int32.onnx"
  engine_file: "superpoint_480x848_int32.engine"
  dla_core: -1

superglue:
  image_width: 848
  image_height: 480
  input_tensor_names:
    - "keypoints_0"
    - "scores_0"
    - "descriptors_0"
    - "keypoints_1"
    - "scores_1"
    - "descriptors_1"
    - "shape"
  output_tensor_names:
    - "scores"
  onnx_file: "superglue_indoor_480x848_int32.onnx"
  engine_file: "superglue_indoor_480x848_int32.engine"
  dla_core: -1

keyframe:
  min_num_match: 30
  max_num_match: 100
  max_distance: 1.5
  max_angle: 0.52

